export const calculatorKeys = [
    { value: "7" },
    { value: "8" },
    { value: "9" },
    { value: "DEL", variant: "secondary" },
    { value: "4" },
    { value: "5" },
    { value: "6" },
    { value: "+" },
    { value: "1" },
    { value: "2" },
    { value: "3" },
    { value: "-" },
    { value: "." },
    { value: "0" },
    { value: "/" },
    { value: "x" },
    { value: "RESET", large: true, variant: "secondary" },
    { value: "=", large: true, variant: "accent" },
  ]
  